### test hello
GET http://localhost:8001/ucenter/hello
Accept: application/json

### test gateway
GET http://localhost:10100/ucenter/hello
Accept: application/json

### test count
GET http://localhost:8001/ucenter/user/count
Accept: application/json

###
GET http://localhost:10100/ucenter/user/count
Accept: application/json

### test registry
POST http://localhost:8001/ucenter/user/registry
Content-Type: application/x-www-form-urlencoded

mobile=139981

###
POST http://localhost:10100/ucenter/user/registry
Content-Type: application/x-www-form-urlencoded

mobile=

### test send code
POST http://localhost:10100/ucenter/user/send-code
Content-Type: application/x-www-form-urlencoded

mobile=13979747386

###
POST http://localhost:10100/ucenter/user/login
Content-Type: application/x-www-form-urlencoded

mobile=13979747386&code=195460