### test hello
GET http://localhost:8001/ucenter/hello
Accept: application/json

### test gateway
GET http://localhost:10100/ucenter/hello
Accept: application/json

### test count
GET http://localhost:8001/ucenter/user/count
Accept: application/json

###
GET http://localhost:10100/ucenter/user/count
Accept: application/json

### test registry
POST http://localhost:8001/ucenter/user/registry
Content-Type: application/x-www-form-urlencoded

mobile=139981

###
POST http://localhost:10100/ucenter/user/registry
Content-Type: application/x-www-form-urlencoded

mobile=

### test send code
POST http://localhost:10100/ucenter/user/send-code
Content-Type: application/json

{
  "mobile": "18485322910"
}

### test sign in
POST http://localhost:10100/ucenter/user/sign-in
Content-Type: application/json

{
  "mobile": "18485322910",
  "code": "666666"
}

### test count
GET http://localhost:10100/ucenter/user/count
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmFtZSI6Ik1OVVNfZWhydDE0IiwiaWQiOiIxNzY2NTM0NDU2MDI3NTE2OTI4IiwiaWF0IjoxNzEwMDc0ODEzLCJleHAiOjE3MTAxNjEyMTMsIm5iZiI6MTcxMDA3NDgxM30.lbY2NNPaU2GBlLbRKtugqs1r08rL6YQMq4vuMXwiHfs

###
POST http://localhost:10100/ucenter/user/sign-in
Content-Type: application/json

{
  "mobile": "13979747386",
  "code": "666666"
}

> {%
    s = JSON.stringify(response.body.data.token);
    // 去掉头尾引号
    client.global.set("token", "Bearer " + s.substring(1, s.length-1))
%}

### test passenger save
POST http://localhost:10100/ucenter/passenger/save
Content-Type: application/json
Authorization: {{token}}

{
  "userId": "18485322910",
  "name": "lisi",
  "type": "2",
  "idCard": ""
}

###
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmFtZSI6Ik1OVVNfZWhydDE0IiwiaWQiOiIxNzY2NTM0NDU2MDI3NTE2OTI4IiwiaWF0IjoxNzEwMDc0ODEzLCJleHAiOjE3MTAxNjEyMTMsIm5iZiI6MTcxMDA3NDgxM30.lbY2NNPaU2GBlLbRKtugqs1r08rL6YQMq4vuMXwiHfs
